### PR TITLE
Refactored the test runner to use a helper class in order to report code coverage

### PR DESCRIPTION
**Pull request by thedrow**
now code coverage can be reported like this:

``` python

with CoverageHandler(...):
      run_tests()
```

### CODE REVIEW

**Comment by ryankask** [comment]
Thanks, Omer, for the patch. 

There were some import errors when I ran the code from this branch. In the future, please test out the code before submitting a pull request.

In addition, the coverage report is incorrect when use this way. I spent some time trying to figure out why but was unable to. Perhaps have a look?

**Comment by thedrow** [comment]
yeh I noticed it later on when I added a test suite for the project (coming up...). Sorry.
I will have a look. Why do you say it is incorrect?

**Comment by ryankask** [comment]
It was reporting lines with class and def statements (among other lines) as not being covered.

I spent a while digging into coverages source code but nothing obvious came up.

Are you using the the `CoverageHandler` class handler independently of the test runner? I'm not sure it needs to be a context manager.

I think a test suite or test project would be great and perhaps more useful than moving a few lines out of `run_tests`.

If you are using it in some other way, I don't think it needs to inherit from coverage (which would likely fix the issue I came across).

Finally, please follow PEP8 style and limit the line length to 79 chars. Probably best to merge in my upstream master branch into whatever you are working on.

Thanks for the contributions! :smile:

**Comment by thedrow** [comment]
Ok, I updated and added lots of stuff. Too many actually. This should be rebased and there are a lot of unit tests to be written, HELP! I'm kinda drowning here.
I just hacked a while and got carried away.
I also finally got around to submit this pull request: https://github.com/jezdez/django-discover-runner/pull/7
Is there somewhere we can discuss my ideas and what needs to be done?

**Comment by ryankask** [comment]
Thanks, Omer. Let me have a look and I will send you my thoughts.

For starters, though, I want to keep things as simple as possible and there are a lot of changes in this patch.

Also, I've made some changes so as you said, it's important to rebase often.

Pause for now, I'll look over it soon and get back to you.

**Comment by thedrow** [comment]
Well, as simple as possible wasn't on my mind. Sorry for that one :)

**Comment by thedrow** [comment]
@ryankask ping :)

**Comment by ryankask** [comment]
Hi Omer,

Things have diverged a bit since the pull request. I've added a little test framework, but mostly to test the discovery functionality.

To be honest, I don't want to add a bunch of command line options that mirror coverage's API and move the main logic to a `CoverageHandler` class.

I _do_, however, want to make make the coverage usage more configurable. I think this should be done using settings, and most of the configuration can be done through one: `COVERAGE_CONFIG_FILE`. If some options turn out to be popular, then those can be added over time as needed (as opposed to because it's there).

Going forward, it would be better to create an issue and discuss an implementation before going ahead with a patch, especially if it involves a ton of changes.

I'm going to close this issue but thanks for contributing.

**Pull request closed without merging**
